### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by mgno100** [mgno100/protospace-38742#1]
# URL
https://protospace-38742.onrender.com

**Comment by shodai-ito** [comment]
@mgno100 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by mgno100** [comment]
ご確認ありがとうございます！

今までの学習成果を活かして、楽しみながら進めていきます！
